### ISSUE TITLE
Undulator radiation widget error while h5 file reading

### ISSUE THREAD

**Issue by jureyherrera** [oasys-kit/XOPPY#115]
There is an error when reading h5 file, which was created by the widget itself:

`Exception                                     Traceback (most recent call last):
  File "~\Miniconda3\lib\site-packages\orangewidget\gui.py", line 2502, in __call__
    self.f(**kwds)
  File "~\Miniconda3\lib\site-packages\orangecontrib\xoppy\widgets\source\undulator_radiation.py", line 356, in read_or_write_file
    raise Exception("Bad data from file.")
Exception: Bad data from file.
`

Cheers, J

**Comment by srio** [comment]
Fixed!

**Comment by pbrumund-73** [comment]
This is great, thank!
